[advisories]
ignore = [
    "RUSTSEC-2023-0071", # rsa: Marvin Attack: potential key recovery through timing sidechannels (No fix available yet)
    "RUSTSEC-2025-0134"  # rustls-pemfile: unmaintained (Transitive dependency)
]
